// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dunumaktzjjzmfmqosgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bnVtYWt0empqem1mbXFvc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NTg3NTMsImV4cCI6MjA0OTEzNDc1M30.DD6NdCUu4eVx1nWpUFXwnCzQsbLvv1Zrizg2t2MzBvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);